### ISSUE TITLE
white/gray area in vim-buftabline

### ISSUE THREAD

**Issue by sandrodz** [aonemd/kuroi.vim#2]
When using vim-buftabline strange white area appears at the top, where buffer tabs live.

<img width="1445" alt="Screen Shot 2019-05-18 at 12 24 42 PM" src="https://user-images.githubusercontent.com/8479569/57966807-ef9ac200-7967-11e9-9a5d-fdd4fecf7e5a.png">

**Comment by aonemd** [comment]
Hello! I think this is an intended behavior by the maintainers of `vim-buftabline` since they are linking the `BufTabLineFill` highlight group to `TabLineFill` https://github.com/ap/vim-buftabline/blob/master/plugin/buftabline.vim#L35.

Anyway, I don't mind changing the theme for Tabs; however, I'm not sure how it should look like. For starters, I can change the fill color to the background color. How about the background color of the currently selected tab? Do you have any suggestions?

**Comment by sandrodz** [comment]
Hey, thanks for the quick reply ^_^

I've no clue actually, I'm not very design-inclined :) But what you propose sounds good.

**Comment by aonemd** [comment]
This is what it looks like after changing the fill color. If it looks okay to you, I will gladly merge it.

![screenshot_2019-05-18_17:52:20](https://user-images.githubusercontent.com/16504838/57972082-2f789e00-7996-11e9-8393-3729b5b711aa.png)

**Comment by sandrodz** [comment]
Looks awesome!

**Comment by aonemd** [comment]
I just pushed the change. Thanks for opening the issue!

**Comment by sandrodz** [comment]
That was quick, thanks!
